var tree={
    val:1,
    left:{
      val:2,
      left: {
        val:4,
        left:{
          val:5,
          left:{},
          right:{}
        },
        right:{
          val:6,
          left:{},
          right:{}
        }
      },
      right: {
        val:7,
        left:{},
        right:{
          val:8,
          left:{},
          right:{}
        }
      }
    },

    right:{
        val:3,
        left:{
          val:9,
          left:{},
          right:{}
        },
        right:{
          val:10,
          left:{
            val:11,
            left:{},
            right:{}
          },
          right:{
            val:12,
            left:{},
            right:{}
          }
        }
    }
}
